### ISSUE TITLE
download URI of version-2.1.3 on dom4j.github.io incorrect

### ISSUE THREAD

**Issue by wspilot** [dom4j/dom4j#126] opened 2021-07-13 16:19 UTC
Should be:
https://github.com/dom4j/dom4j/releases/download/version-2.1.3/dom4j-2.1.3.jar
(this one does the download.)

**Comment by pzhlkj6612** [comment] 2021-08-16 09:54
Hi. I think this issue is a duplicate of #90 .

**Closed** 2021-08-16 10:00 UTC
Labels: duplicate
