### ISSUE TITLE
Adding support for new Jakarta Namespace (jakarta.xml.bind)

### ISSUE THREAD

**Issue by reinhapa** [dom4j/dom4j#168] opened 2023-08-31 14:33 UTC
With the namespace change to the Jakarta Project, the XML Binding API has changed and there is currently no support for this.

**Comment by rkottmann** [comment] 2023-12-14 10:44
duplicate of https://github.com/dom4j/dom4j/issues/132

**Closed** 2024-01-09 12:49 UTC
